url: https://www.robissonoliveira.com.br
name: Robisson Oliveira
description: >
  Desenvolvimento de software, internet
  marketing e gerenciamento de projetos
  
sass:
  sass_dir: _sass
  style: compressed
